name: edutab
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ui and icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  carousel_slider: ^5.1.1
  font_awesome_flutter: ^10.7.0

  # state management
  provider: ^6.1.1

  # Firebase backend
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2


  # File Handling
  file_picker: ^10.3.3
  image_picker: ^1.0.7
  path_provider: ^2.1.2

  # Network & Loading
  http: ^1.2.0
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.0
  intl: ^0.20.2
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/plane.png
    - assets/images/task1.png
    - assets/images/task2.png
    - assets/images/male_teacher.png
    - assets/images/dsa.png
    - assets/images/oop.png
    - assets/images/os.png
    - assets/images/web.png
    - assets/images/database.png
    - assets/images/teacher_profile.png
    - assets/images/test_image.png
    - assets/images/material_image.png
    - assets/images/owl.png
    # - assets/icons/
  
  # Example for custom fonts (optional)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
